### ISSUE TITLE
missing app.bundle.js

### ISSUE THREAD

**Issue by micahstubbs** [samaleksov/d3-chainsaw#1]
when I run `npm start` and navigate to [localhost:8081](localhost:8081) I see these errors:

![screen shot 2016-11-21 at 8 19 44 pm](https://cloud.githubusercontent.com/assets/2119400/20510828/43b83cac-b028-11e6-9ad3-fd55d5ea7e8d.png)

the page looks like this:

![screen shot 2016-11-21 at 8 24 26 pm](https://cloud.githubusercontent.com/assets/2119400/20510873/85a7dd34-b028-11e6-88bf-c925e19fdd35.png)

**Comment by micahstubbs** [comment]
if `mkdir dist` from the root of the project, all is well. the page now renders 🎉 

![screen shot 2016-11-21 at 8 52 09 pm](https://cloud.githubusercontent.com/assets/2119400/20511359/893baa9e-b02c-11e6-84c6-45eb05a05895.png)

**Comment by micahstubbs** [comment]
would be nice to check the filesystem and create that `dist` directory if it does not already exist

**Comment by catinthesack** [comment]
Hello Micah,
thanks for noticing.

I've added the procompiled assests in the dist forlder with [688539a42df011d9834fdb48a492b62da19add7b](https://github.com/samaleksov/d3-chainsaw/commit/688539a42df011d9834fdb48a492b62da19add7b)
